---
- name: Applying proxy settings to {{ bash_proxy_dest }}
  tags: bash-proxy
  template:
    src: bash_proxy.j2
    dest: "{{ bash_proxy_dest }}"
    owner: "{{ bash_proxy_owner }}"
    group: "{{ bash_proxy_group }}"
    mode: "{{ bash_proxy_mode }}"
...
